### DISCUSSION TITLE
S7 - Vacuum and mop or just vacuum.

### DISCUSSION THREAD

**Discussion by SHJ234** [humbertogontijo/homeassistant-roborock#119] [Ideas]
Hi,

Thank you for the great work !
I see in the atribute list there is listed:
Mop mode list - standard, deep, deep_plus, custom
Mop intensity list - off, mild, moderate, intense, custom

Is there any plans to make you able to control this? Then it can be selected to only mop or vacuum or both.

**Comment by jdejaegh** [comment]
You can control this via a service call.  The integration adds some services under the `roborock` domain.  Here are two examples of service calls to change the mop mode and intensity.  

The Home Assistant UI is quite intuitive once you know what services you are looking for: the different values for the options are shown when going under Developer tools > Services and selecting either of the services.

```yml
service: roborock.vacuum_set_mop_mode
data:
  mop_mode: deep
target:
  entity_id: vacuum.roborock_s7
```

```yml
service: roborock.vacuum_set_mop_intensity
data:
  mop_intensity: mild
target:
  entity_id: vacuum.roborock_s7
 ```

**Comment by Eisoniq** [comment]
Yeah, I'm also wondering how to setup an automation to have it just vacuum using Max+ when I leave?
Tried vacuum.set_fan_speed but nothing I tried with it worked, trying to set roborock.vacuum_set_mop_intensity to off gives me errors as well, I'm probably just missing/not understanding something.

**Reply by jdejaegh** [reply]
I had a similar use case I configured a few versions ago for my S7.

I realized that you cannot change mop mode and intensity when the mop is not on the robot.  I had to first check it the mop was installed before issuing the command to disable mopping.  If the mop is not installed it obviously cannot mop.

As the script was written when the `roborock.vacuum_set_mop_intensity` was not yet introduced, I had to use the `vacuum.send_command` to disable mopping.  Although it still works, I have to update the script to use the new `roborock.*` services are they are easier to use.

Setting up an automation like you describe seems possible and I would proceed like so:

- Set fan speed to Max
- Check if mop is installed and if so, disable mopping
- Start the vacuum

Are you sure 'Max+' is a valid value for the fan speed of you vacuum?  Mine goes up to Max but not Max+ and when I call the service to set it to Max+, the service call works but the Roborock app starts to crash.

Here is the service call I used to set the fan speed to Max:
```yml
service: vacuum.set_fan_speed
data:
  fan_speed: Max
target:
  entity_id: vacuum.roborock_s7
```

**Reply by Eisoniq** [reply]
Thank you very much, that works great.

**Reply by modo1302** [reply]
hey!

found this thread as i was trying to set up a similar scenario.
Just want to add: for the Max+ fan speed you need to enter **max_plus** value - works for me :)

**Reply by tamueller** [reply]
Hi, I hope it's ok to reuse this old question, but I have trouble setting the mop mode for my S8 manually.
Setting fan speed works fine, and using the lovelace-xiaomi-vacuum-map-card it's possible to set the mop mode, but I can't figure out how to do it myself.
My roborock domain only has the following service calls:
vacuum_clean_zone, vacuum_clean_segment, vacuum_load_multi_map and 4 vacuum_remote_* commands.

The vacuum domain has "set_fan_speed" but no mop mode. 
What do I need to do, so that the set_mop_mode and set_mop_intensity service calls are added?

**Reply by Eisoniq** [reply]
For my S7 I have to select Device in the action section, and there I can select the actions for the device, like mop mode and mop intensity, it's not a service call like for vacuuming.

**Reply by dudenell** [reply]
Old thread but I wanted to help with mop mode. Here's a service call that will change the mop intensity:

```
service: select.select_option
target:
  entity_id: select.alfred_mop_intensity
data:
  option: moderate

```

Change the vacuum name with your own.

**Reply by theAshbringer** [reply]
For everyone who got stuck with this script, change `data` to `service_data`. It should help.
```
service: select.select_option
target:
  entity_id: select.roborock_s7_maxv_mop_intensity
service_data:
  option: moderate
```
