### DISCUSSION TITLE
Multi Floor Home Change Map

### DISCUSSION THREAD

**Discussion by dleggen** [humbertogontijo/homeassistant-roborock#151] [Q&A] [answered]
I have a multi floor home and I am not able to figure out how to change the map being used. Can I do that in HA or do I need to use the roborock app?

**Comment by jdejaegh** [comment]
**See @humbertogontijo's [reply](https://github.com/humbertogontijo/homeassistant-roborock/discussions/151#discussioncomment-4709624) that is more up-to-date than mine.**

You can use a service call to change the map.  Here is an example.

```yml
service: vacuum.send_command
data:
  command: load_multi_map
  params: 0
target:
  entity_id: vacuum.roborock_s7
```

The `params` contains the index of the map you want to load, starting from 0.  The `entity_id` should be your vacuum.

Please note that there used to be a delay for the map to update in the integration (the command is executed but the map shown is not refreshed quickly).  One way to be sure that the command is executed when testing this is to have your Roborock app opened next to you and see the map updating within seconds.

There have been multiple issues discussing the map not refreshing but I did not follow everything, maybe the issue is solved in the latest version.

**Comment by humbertogontijo** [comment, marked as answer]
Use the new service instead. It loads the map right away
```
service: roborock.camera_load_multi_map
data:
  map_flag: 0
target:
  entity_id: camera.roborock_s7_maxv
```

**Reply by jdejaegh** [reply]
I just updated my config to use this service instead of the older one and it's working just fine, even faster to update the map than Roborock's app.  Thanks!

**Reply by Fuchschr11** [reply]
When I call this:

`service: roborock.camera_load_multi_map
data:
  map_flag: 0
target:
  device_id: a88f4bcff546967f958472d3c2ba3332
`
Device_ID is my Roborock S7 it works. 

But calling it with map_flag: 1
the error 
`Failed to call service roborock.camera_load_multi_map. Map flag 1 is invalid. Available map flags for device are {'Erdgeschoss ': 0`
is shown.

I have 4 maps.

Any ideas?

**Reply by Fuchschr11** [reply]
Works now with:

- icon: mdi:alpha-o-box-outline
    tooltip: Obergeschoss
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      target:
        entity_id: camera.roborock_s7_pro_ultra_map
      service_data:
        map_flag: 3


Is there a way the get the map_flag as a condition within an automation?

Thank you.

**Comment by AKruimink** [comment]
In case this helps anyone else, as I was still slightly confused after reading these comments,
In my case im using the Lovelace Vacuum Map card.

When editing the card open the text editor (might have to click the Generate Static Config first), than at the bottom of the icons section I added

```
  - icon: mdi:numeric-0-box
    tooltip: Downstairs
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      service_data:
        map_flag: 0
      target:
        entity_id: camera.roborock_s7_map
  - icon: mdi:numeric-1-box
    tooltip: Upstairs
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      service_data:
        map_flag: 1
      target:
        entity_id: camera.roborock_s7_map
```

Which added 2 buttons to the card that let me quick swap between my 2 maps using the service outlined by @humbertogontijo 
![image](https://user-images.githubusercontent.com/43521957/222780653-a04795a9-628a-4251-b7cf-30460577316f.png)
