### DISCUSSION TITLE
Enable or disable mopping

### DISCUSSION THREAD

**Discussion by randyesperben** [humbertogontijo/homeassistant-roborock#157] [Q&A]
Hi community!

I would like to set mop and vacuum, o just vacuum. How could I achieve this?

Thanks in advance!

**Comment by Antexa** [comment]
Hi, 

I would like to perform this aswell :)

**Reply by humbertogontijo** [reply]
You can do that using services roborock.vacuum_set_mop_mode and roborock.vacuum_set_fan_speed.
roborock.vacuum_set_mop_mode to off will stop the mopping, roborock.vacuum_set_fan_speed to off will stop vacuuming

**Reply by Antexa** [reply]
Sounds really good 👍 

```
if:
  - condition: time
    weekday:
      - mon
      - wed
      - fri
then:
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: intense
    target:
      entity_id: vacuum.roborock_s7_maxv
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: vacuum.send_command
    data:
      params:
        - 20
      command: app_segment_clean
    target:
      entity_id: vacuum.roborock_s7_maxv
else:
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: "off"
    target:
      entity_id: vacuum.roborock_s7_maxv
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: vacuum.send_command
    data:
      params:
        - 20
      command: app_segment_clean
    target:
      entity_id: vacuum.roborock_s7_maxv
```

Any ideas on adding more segments during a current clean ?
