### DISCUSSION TITLE
The Ultimate Roborock S7 MaxV Ultra Setup Questions

### DISCUSSION THREAD

**Discussion by NissarAK84** [humbertogontijo/homeassistant-roborock#202] [Q&A]
Hi,
First of all, I am really happy to see such an amazing community that helps out everyone.

I have jumped into the HA bandwagon for 2 weeks now, and although I have many times considered quitting, it still pulls me back in :)

We have a Roborock S7 MaxV Ultra, and although we like it so much, my better half does not feel it is quite intuitive, and she keeps texting me during my work day to start vacuuming or mopping here and there. So I figured, why not get HA and along with all the other stuff we could do, I could also setup a dashboard for the vacuum cleaning and mopping.

OK, enough talk.

My goal is:

- [ ] - Have a dedicated Dashboard view for the Roborock S7 MaxV Ultra with the vacuum card and all controls, one card for Vacuum Rooms with a dropdown, one for the Mop Rooms with a dropdown, one for Vacuum Zones with a dropdown and one for the Mop Zones with a dropdown.
- [ ] - In the individual views for each of the rooms in the house, I want to have 3 buttons: Vacuum the Room, Mop the Room, Clean the Room (Vacuum & Mop).
- [ ] - In the individual views for each of the zones in the house, I want to have 3 buttons: Vacuum the Zone, Mop the Zone, Clean the Zone (Vacuum & Mop).
- [ ] - Expose the Vacuum / Mop / Clean entities for rooms and zones to Google Home through Nabu Casa, and setup routines in Google Home with voice commands and then my wife can just tell our Sonos speakers to Vacuum / Mop / Clean particular room(s) or zone(s).

NOTES:
- I have 12 rooms and 4 zones.
- I have identified the segment numbers for the rooms, and therefore am not using the coordinates (although I spent hours on that)
- I will use the Living Room and the zone it is a part of called Living Area as an example for this post.

What I have done so far:

I initially had setup the Xiaomi Integration, and followed this guide:

[https://smarthomepursuits.com/how-to-setup-configure-roborock-s7-with-home-assistant/](url)

But then I got confused just around step 4 and decided to go with the Roborock Integration, and replace my codes from Xiaomi to Roborock. Reason for jumping ship was, because I was loosing out on critical WAF points because on her Roborock App the device showed as offline and besides we lost the camera live feed to look after our pets.

So, Roborock Integration is setup and looks fine. I have one device and 22 entitties.

From the technical perspective this is what I have done:

**1)** Created 4 Helpers: Vacuum Rooms, Mop Rooms, Vacuum Zones and Mop Zones. These are called as such:
- input_select.vacuum_rooms
- input_select.mop_rooms
- input_select.vacuum_zone
- input_select.mop_zone

The "_rooms" input selects consist of 12 rooms each, while the "_zone" input selects have 4 zones each.

**2)** Created 32 Scripts: 12 for vacuuming individual rooms, 4 for vacuuming individual zones, 12 for mopping individual rooms and 4 for mopping individual zones. Total of 32!

**- YAML for the Vacuum Living Room Script:**
```
alias: Vacuum Living Room
sequence:
  - service: roborock.vacuum_remote_control_stop
    target:
      entity_id: vacuum.roborox
    data: {}
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
    enabled: true
  - service: roborock.vacuum_set_fan_speed
    data:
      fan_speed: max_plus
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: "off"
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_clean_segment
    target:
      entity_id: vacuum.roborox
    data:
      segments: 20
mode: single
icon: mdi:sofa
```
**- YAML for the Mop Living Room Script:**
```
alias: Mop Living Room
sequence:
  - service: roborock.vacuum_remote_control_stop
    target:
      entity_id: vacuum.roborox
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: roborock.vacuum_set_fan_speed
    data:
      fan_speed: "off"
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: intense
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_set_mop_mode
    data:
      mop_mode: deep_plus
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_clean_segment
    target:
      entity_id: vacuum.roborox
    data:
      segments:
        - 20
mode: single
icon: mdi:sofa
```
**- YAML for the Vacuum Living Area Script:**
```
alias: Vacuum Living Area
sequence:
  - service: roborock.vacuum_remote_control_stop
    target:
      entity_id: vacuum.roborox
    data: {}
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
    enabled: true
  - service: roborock.vacuum_set_fan_speed
    data:
      fan_speed: max_plus
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: "off"
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_clean_segment
    target:
      entity_id: vacuum.roborox
    data:
      segments:
        - 20
        - 21
        - 22
mode: single
icon: mdi:robot-vacuum
```
**- YAML for the Mop Living Area Script:**
```
alias: Mop Living Area
sequence:
  - service: roborock.vacuum_remote_control_stop
    target:
      entity_id: vacuum.roborox
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: roborock.vacuum_set_fan_speed
    data:
      fan_speed: "off"
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: intense
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_set_mop_mode
    data:
      mop_mode: deep_plus
    target:
      entity_id: vacuum.roborox
  - service: roborock.vacuum_clean_segment
    target:
      entity_id: vacuum.roborox
    data:
      segments:
        - 20
        - 21
        - 22
mode: single
icon: mdi:robot-vacuum-variant
```
**3)** Created 4 Automations: one Automation to run the Vacuum Rooms scripts, one for Mop Rooms, one for Vacuum Zones and one for Mop Zones.

**- YAML for Vacuum Rooms Automation:**
```
alias: Vacuum Rooms
description: ""
trigger: []
condition: []
action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if states.input_select.vacuum_rooms.state == "Kitchen" %}
        script.vacuum_kitchen {% elif states.input_select.vacuum_rooms.state ==
        "Dining Room" %} script.vacuum_dining_room {% elif
        states.input_select.vacuum_rooms.state == "Living Room" %} script.vacuum_living_room
        {% elif states.input_select.vacuum_rooms.state == "Hallway" %}
        script.vacuum_hallway {% elif states.input_select.vacuum_rooms.state ==
        "Master Bedroom" %} script.vacuum_master_bedroom {% elif
        states.input_select.vacuum_rooms.state == "Nursery" %}
        script.vacuum_nursery {% elif
        states.input_select.vacuum_rooms.state == "Kids Room" %}
        script.vacuum_kids_room {% elif
        states.input_select.vacuum_rooms.state == "Master Bathroom" %}
        script.vacuum_master_bathroom {% elif states.input_select.vacuum_rooms.state
        == "Kids Bathroom" %} script.vacuum_kids_bathroom {% elif
        states.input_select.vacuum_rooms.state == "Office" %}
        script.vacuum_office {% elif states.input_select.vacuum_rooms.state ==
        "Washroom" %} script.vacuum_washroom {% elif
        states.input_select.vacuum_rooms.state == "Make-Up Studio" %}
        script.vacuum_make_up_studio {% endif %}
mode: single
```
**- YAML for Mop Rooms Automation:**
```
alias: Mop Rooms
description: ""
trigger: []
condition: []
action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if states.input_select.mop_rooms.state == "Kitchen" %}
        script.mop_kitchen {% elif states.input_select.mop_rooms.state ==
        "Dining Room" %} script.mop_dining_room {% elif
        states.input_select.mop_rooms.state == "Living Room" %} script.mop_living_room
        {% elif states.input_select.mop_rooms.state == "Hallway" %}
        script.mop_hallway {% elif states.input_select.mop_rooms.state ==
        "Master Bedroom" %} script.mop_master_bedroom {% elif
        states.input_select.mop_rooms.state == "Nursery" %}
        script.mop_nursery {% elif
        states.input_select.mop_rooms.state == "Kids Room" %}
        script.mop_kids_room {% elif
        states.input_select.mop_rooms.state == "Master Bathroom" %}
        script.mop_master_bathroom {% elif states.input_select.mop_rooms.state
        == "Kids Bathroom" %} script.mop_kids_bathroom {% elif
        states.input_select.mop_rooms.state == "Office" %}
        script.mop_office {% elif states.input_select.mop_rooms.state ==
        "Washroom" %} script.mop_washroom {% elif
        states.input_select.mop_rooms.state == "Make-Up Studio" %}
        script.mop_make_up_studio {% endif %}
mode: single
```
**- YAML for Vacuum Zones Automation:**
```
alias: Vacuum Zones
description: ""
trigger: []
condition: []
action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if states.input_select.vacuum_zones.state == "Living Area" %}
        script.vacuum_living_area {% elif
        states.input_select.vacuum_zones.state == "Rooms" %}
        script.vacuum_rooms {% elif states.input_select.vacuum_zones.state
        == "Bathrooms" %} script.vacuum_bathrooms {% elif
        states.input_select.vacuum_zones.state == "Hallway & Washroom" %}
        script.vacuum_hallway_and_washroom {% endif %}
mode: single
```
**- YAML for Mop Zones Automation:**
```
alias: Mop Zones
description: ""
trigger: []
condition: []
action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if states.input_select.mop_zones.state == "Living Area" %}
        script.mop_living_area {% elif
        states.input_select.mop_zones.state == "Rooms" %}
        script.mop_rooms {% elif states.input_select.mop_zones.state
        == "Bathrooms" %} script.mop_bathrooms {% elif
        states.input_select.mop_zones.state == "Hallway & Washroom" %}
        script.mop_hallway_and_washroom {% endif %}
mode: single
```
**4)** On my Dashboard I have a dedicated view for my Roborock S7 MaxV Ultra. With 4 cards with a dropdown lists based on the Input Selects: one for Vacuum Rooms, one for Mop Rooms, one for Vacuum Zones and one for Mop Zones.

**- YAML for the Vacuum Rooms card:**
```
type: grid
cards:
  - type: entities
    entities:
      - entity: input_select.vacuum_rooms
        secondary_info: none
    title: Vacuum
    state_color: true
  - square: false
    columns: 3
    type: grid
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: automation.trigger
          target:
            entity_id:
              - automation.vacuum_rooms
          data:
            skip_condition: false
        entity: vacuum.roborox
        name: Start
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: vacuum.pause
          target:
            entity_id: vacuum.roborox
          data: {}
        name: Pause
        entity: vacuum.roborox
        icon: mdi:robot-vacuum-off
        show_state: false
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: vacuum.return_to_base
          service_data: {}
          target:
            entity_id: vacuum.roborox
        entity: vacuum.roborox
        icon: mdi:garage-variant
        name: Base
square: false
columns: 1
```
**- YAML for the Mop Rooms card:**
```
type: grid
cards:
  - type: entities
    entities:
      - entity: input_select.mop_rooms
    state_color: true
    title: Mop
  - square: false
    columns: 3
    type: grid
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: automation.trigger
          target:
            entity_id: automation.mop_rooms
          data:
            skip_condition: false
        entity: vacuum.roborox
        name: Start
        icon: mdi:robot-vacuum-variant
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: vacuum.pause
          target:
            entity_id: vacuum.roborox
          data: {}
        name: Pause
        entity: vacuum.roborox
        icon: mdi:robot-vacuum-variant-off
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: vacuum.return_to_base
          target:
            entity_id: vacuum.roborox
          data: {}
        name: Base
        entity: vacuum.roborox
        icon: mdi:garage-variant
square: false
columns: 1
```
The YAML for the Vacuum and Mop cards are similar to the above, the only difference being that they refer to their own respective Input Selects.

5) I started setting up the Xiaomi Vacuum Card, but couldn't make sense of it. Then, after changing to the Roborock Integration, I did some changes and have a card on the same dedicated view for the Roborock with the following YAML:

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborox
map_source:
  camera: camera.roborox_map
  show_state: true
  show_name: true
  camera_view: live
  type: picture-entity
  entity: camera.roborox_map
camera_image: camera.roborox_map
calibration_source:
  camera: true
vacuum_platform: send_command
title: Overview
map_modes:
  - name: Rooms
    template: vacuum_clean_segment
    predefined_selections:
      - id: 16
        icon:
          name: mdi:coat-rack
          x: 31350
          'y': 26675
        label:
          text: Hallway
          x: 31350
          'y': 26675
          offset_y: 35
        outline:
          - - 24650
            - 24450
          - - 38050
            - 24450
          - - 38050
            - 28900
          - - 24650
            - 28900
      - id: 17
        icon:
          name: mdi:washing-machine
          x: 26800
          'y': 23425
        label:
          text: Washroom
          x: 26800
          'y': 23425
          offset_y: 35
        outline:
          - - 24850
            - 21500
          - - 28750
            - 21500
          - - 28750
            - 25350
          - - 24850
            - 25350
      - id: 19
        icon:
          name: mdi:chair-rolling
          x: 29800
          'y': 23525
        label:
          text: Office
          x: 29800
          'y': 23525
          offset_y: 35
        outline:
          - - 28750
            - 21800
          - - 30850
            - 21800
          - - 30850
            - 25250
          - - 28750
            - 25250
      - id: 20
        icon:
          name: mdi:sofa
          x: 43775
          'y': 29350
        label:
          text: Living Room
          x: 43775
          'y': 29350
          offset_y: 35
        outline:
          - - 40250
            - 25150
          - - 47300
            - 25150
          - - 47300
            - 33550
          - - 40250
            - 33550
      - id: 21
        icon:
          name: mdi:chef-hat
          x: 39025
          'y': 22400
        label:
          text: Kitchen
          x: 39025
          'y': 22400
          offset_y: 35
        outline:
          - - 37650
            - 17800
          - - 40400
            - 17800
          - - 40400
            - 27000
          - - 37650
            - 27000
      - id: 22
        icon:
          name: mdi:silverware-clean
          x: 43425
          'y': 21375
        label:
          text: Dining Room
          x: 43425
          'y': 21375
          offset_y: 35
        outline:
          - - 40550
            - 17600
          - - 46300
            - 17600
          - - 46300
            - 25150
          - - 40550
            - 25150
      - id: 23
        icon:
          name: mdi:face-woman
          x: 32300
          'y': 23550
        label:
          text: Kids Room
          x: 32300
          'y': 23550
          offset_y: 35
        outline:
          - - 30850
            - 21850
          - - 33750
            - 21850
          - - 33750
            - 25250
          - - 30850
            - 25250
      - id: 24
        icon:
          name: mdi:teddy-bear
          x: 35950
          'y': 23600
        label:
          text: Nursery
          x: 35950
          'y': 23600
          offset_y: 35
        outline:
          - - 34600
            - 21900
          - - 37300
            - 21900
          - - 37300
            - 25300
          - - 34600
            - 25300
      - id: 25
        icon:
          name: mdi:bed-king
          x: 37975
          'y': 30275
        label:
          text: Master Bedroom
          x: 37975
          'y': 30275
          offset_y: 35
        outline:
          - - 34150
            - 26950
          - - 41800
            - 26950
          - - 41800
            - 33600
          - - 34150
            - 33600
      - id: 26
        icon:
          name: mdi:lipstick
          x: 28250
          'y': 30525
        label:
          text: Make-Up Studio
          x: 28250
          'y': 30525
          offset_y: 35
        outline:
          - - 24800
            - 27000
          - - 31700
            - 27000
          - - 31700
            - 34050
          - - 24800
            - 34050
      - id: 27
        icon:
          name: mdi:bathtub-outline
          x: 30475
          'y': 29275
        label:
          text: Kids Bathroom
          x: 30475
          'y': 29275
          offset_y: 35
        outline:
          - - 29050
            - 26950
          - - 31900
            - 26950
          - - 31900
            - 31600
          - - 29050
            - 31600
      - id: 28
        icon:
          name: mdi:bathtub
          x: 32875
          'y': 28725
        label:
          text: Master Bathroom
          x: 32875
          'y': 28725
          offset_y: 35
        outline:
          - - 31500
            - 27100
          - - 34250
            - 27100
          - - 34250
            - 30350
          - - 31500
            - 30350
  - name: Select Area
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: roborock.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
map_locked: true
two_finger_pan: false
tiles:
  - tile_id: battery_level
    entity: vacuum.roborox
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.roborox
    label: Speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      'off': Off
      silent: Silent
      balanced: Balanced
      turbo: Turbo
      max: Max
      max_plus: Max+
      custom: Custom
  - tile_id: sensor_dirty_left
    label: Sensor Left
    unit: t
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborox
    entity: sensor.roborox_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter Left
    unit: t
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborox
    entity: sensor.roborox_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Main Brush Left
    unit: t
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.roborox
    entity: sensor.roborox_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Side Brush Left
    unit: t
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborox
    entity: sensor.roborox_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: cleaning_count
    label: Cleaning Count
    entity: sensor.roborox_total_clean_count
    icon: mdi:counter
    precision: 0
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborox
        value_not: cleaning
      - entity: vacuum.roborox
        value_not: error
      - entity: vacuum.roborox
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborox
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborox
        value_not: docked
      - entity: vacuum.roborox
        value_not: idle
      - entity: vacuum.roborox
        value_not: error
      - entity: vacuum.roborox
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborox
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborox
        value_not: docked
      - entity: vacuum.roborox
        value_not: idle
      - entity: vacuum.roborox
        value_not: error
      - entity: vacuum.roborox
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborox
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborox
        value_not: docked
      - entity: vacuum.roborox
        value_not: returning
    tooltip: Returning
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborox
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborox
        value_not: docked
      - entity: vacuum.roborox
        value_not: error
      - entity: vacuum.roborox
        value_not: cleaning
      - entity: vacuum.roborox
        value_not: returning
    tooltip: Clean Spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborox
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborox
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: 'off'
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: silent
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: balanced
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: balanced
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: turbo
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: turbo
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: max
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: max
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: max_plus
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: max_plus
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: custom
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value: custom
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: 'off'
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: 'off'
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: silent
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: balanced
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: turbo
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: max
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: max_plus
      - entity: vacuum.roborox
        attribute: fan_speed
        value_not: custom
    tooltip: Set Fan Speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborox
        fan_speed: 'off'
```
It seems to work, I think.

**6)** In the Living Room view of my dashboard, I created 2 cards: Vacuum Living Room and Mop Living Room:

**- YAML for Vacuum Living Room card:**
```
square: false
columns: 1
type: grid
cards:
  - type: custom:mushroom-title-card
    title: Roborox
    title_tap_action:
      action: none
    subtitle_tap_action:
      action: none
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-entity-card
        entity: script.vacuum_living_room
        icon: mdi:robot-vacuum
        layout: vertical
        icon_color: orange
        tap_action:
          action: toggle
      - type: custom:mushroom-entity-card
        entity: script.mop_living_room
        icon: mdi:robot-vacuum-variant
        icon_color: orange
        layout: vertical
        tap_action:
          action: toggle
```

**7)** I exposed the entities to Google Home, where they showed up as scenes. Then I set up a routine to run these based on what I say. Example:
- "Hey Google Vacuum Living Room" runs the Vacuum Living Room scene
- "Hey Google Mop Living Room" runs the Mop Living Room scene
- "Hey Google Clean Living Room" runs the Vacuum Living Room and after that Mop Living Room scenes. That is because I selected these two scenes as actions in my Google Home routine in that order

**OK**. Sorry for such a long post.

Now, my issues:

I initiate Vacuum Living Room either through Google Assistent, the dedicated view for the Roborock or the Living Room view in my HA Dashboard. I hear the chime 2 times, after 2 second pause I can validate in the Roborock App that it is in Max+ Vacuum Mode Only state and goes to vacuum the Living Room. Good, right? No.

- If I then initiate the Mop Living Room option, I hear the chimes, but the robot is still going for the vacuuming job. It is ignoring my command completely. Only way to stop it is to press Pause either on the Roborock App or the HA Dashboard.
- After pausing, if I then press Mop Living room, I hear the 4 chimes and it goes to Vacuum & Mop default mode. I have to press the Mop Living Room once again for it register the Deep+ Mop Ony state.
- When I then pause the mopping and press the Vacuum Living Room, same story. It resets to default mode, and I have to press the Vacuum Living Room once again for it to register that.

I tried to change my scripts to basically run the same sequence twice. The amount of chimes is now multiplied by 2 (4 in total) and sometimes it does what I want (Vacuum Only or Mop Only), often times it just resets to default mode.

- Finally, when initiating the multiple room or zone vacuuming / mopping, it simply forgets to go to charge. For instance, you tell her to vacuum Living Room, Dining Room and 2 bedrooms (individual rooms not on same zone), if the battery gets below 20%, well it just keeps on until it's dead.

So, now I have my entire setup and my issues here.

I hope someone can help me sort this out (I know I am 90% there!), and I hope others find the codes useful!

Thank you!
