### DISCUSSION TITLE
Washing the mob before carrying S7 Pro to different floor

### DISCUSSION THREAD

**Discussion by Fuchschr11** [humbertogontijo/homeassistant-roborock#207] [General]
When I would like to clean a different floor, Roborock S7 Pro Ultra needs to wash the mob first.
I would like to do this in HA. I do not find a command to Initiate washing the mob.

Any Ideas?
How is the best workflow for initiating cleaning a different floor (need to carry the robot upstairs).

**Comment by sophof** [comment]
This is what I use (make sure you have the right map loaded):
``` yaml
service: vacuum.send_command
data:
  command: app_start_wash
target:
  entity_id: vacuum.roborock
```

And here is an example that I use for a different floor (not, the clean twice aspect doesn't seem to work for me currently):
``` yaml
alias: Maak slaapkamer en badkamer schoon (2x)
sequence:
  - service: roborock.camera_load_multi_map
    data:
      map_flag: 2
    target:
      entity_id: camera.roborock_map
  - service: roborock.vacuum_clean_segment
    data:
      segments:
        - 16
        - 17
        - 16
        - 17
    target:
      entity_id: vacuum.roborock
  - wait_for_trigger:
      - platform: state
        entity_id:
          - vacuum.roborock
        to: returning
        for:
          hours: 0
          minutes: 0
          seconds: 10
    timeout:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: vacuum.stop
    data: {}
    target:
      entity_id: vacuum.roborock
mode: single
icon: mdi:broom
```
I have simply made a separate button for each script in my frontend.
