### DISCUSSION TITLE
Wash mop command?

### DISCUSSION THREAD

**Discussion by CZonin** [humbertogontijo/homeassistant-roborock#655] [Q&A]
Does anyone know if there's a command to have the Roborock S7 MaxV Ultra wash the mop? I found a command to empty the bin in another thread that works, but nothing about washing the mop:

```
service: vacuum.send_command
data:
  command: app_start_collect_dust
target:
  entity_id: vacuum.vacuum_name
```

I've tried these without any luck:

```
service: vacuum.send_command
data:
  command: app_start_wash_mop
target:
  entity_id: vacuum.vacuum_name
```

```
service: vacuum.send_command
data:
  command: app_start_clean_mop
target:
  entity_id: vacuum.vacuum_name
```
