### ISSUE TITLE
Map is not updating live

### ISSUE THREAD

**Issue by samuolis** [humbertogontijo/homeassistant-roborock#134]
Previously with xiaomi integration map was updated live, now it is not updating ar all or only after finishing vacuuming. 

I have roborock s7

**Comment by samuolis** [comment]
I see that only after reloading integration map is updated

**Comment by Caine72** [comment]
I see the same issue. 
Calling homeassistant.update_entity service perform a single update of the image.
Calling  camera.turn_on (which should enable the polling) seemed to update the image once when my s5 max was running but not after it paused.
 
In camera.py's init method i can see that `self._should_poll = True` so I assume polling should be enabled by default.
I noticed the commenting in the turn_on/off was inverted. =)

And I have not managed to get any further with my investigation as the battery was depleted ... never noticed i had such issues before enabling the intergration though .... but that might be a different topic....

**Comment by Maarten112** [comment]
I experience the same issue. Also with a Roborock S7.

Map is updated after reconfiguring the integration or once after calling update_entity_service as @Caine72 suggested. One time it suddenly was updated live...but it's stopped updating again.

**Comment by medfiras** [comment]
Actually there is a bug with refresh map.
There is 2 workaround [here](https://github.com/humbertogontijo/homeassistant-roborock/issues/69#issuecomment-1373921163) and [here](https://github.com/humbertogontijo/homeassistant-roborock/issues/69#issuecomment-1374008008)

**Comment by Maarten112** [comment]
> Actually there is a bug with refresh map. There is 2 workaround [here](https://github.com/humbertogontijo/homeassistant-roborock/issues/69#issuecomment-1373921163) and [here](https://github.com/humbertogontijo/homeassistant-roborock/issues/69#issuecomment-1374008008)

Hi medfiras,

That's great! I used your node-red flow and edited for the right entities / camera...working great for now till the integration fixed the live update ! :) 

Thanks!

**Comment by Caine72** [comment]
For those who automate in HA i did it like this. Mind you I have not tested it fully yet... but should work ok. 

```
alias: Roborock - Update map
description: Workaround until manual update is fixed.
trigger:
  - platform: state
    entity_id:
      - vacuum.<your vacuum entity>
    to: cleaning
condition: []
action:
  - repeat:
      while:
        - condition: state
          entity_id: vacuum.<your vacuum entity>
          state: cleaning
      sequence:
        - service: homeassistant.update_entity
          data: {}
          target:
            entity_id: camera.<your camera entity>
        - delay:
            hours: 0
            minutes: 0
            seconds: 5
            milliseconds: 0
mode: single

```
