### ISSUE TITLE
Repeated action of several parts with vacuum_clean_segment

### ISSUE THREAD

**Issue by Alindil** [humbertogontijo/homeassistant-roborock#159]
When we have 1 room, putting 2 times the id of the room in the list of the parameter Segments, repeats the action 1 time. On the other hand, if there are several parts, only the last part in the list will be repeated in the right order.

Example: 
Segments: [25,16,25,16]
The vacuum cleaner will suck in part 25, then 2 times part 16 is returned to part 25.

I tried to change the order of calling the parts ([25,25,16,16] or [25,16,16,25] but no action in the order the part 25 x2 and the part 16 x2

**Comment by Xyaren** [comment]
Do we know how the official app does it ? 
Seems to be working there ?

**Comment by knecht-d** [comment]
First of all, thanks @humbertogontijo for this great integration.

I've had the same issue and found this thread in the home assistant community:
https://community.home-assistant.io/t/roborock-xiaomi-vacuum-integration-needs-a-fix-add-repeat-to-segments/361358/6

Instead of repeating the segment multiple times like this:
```yaml
service: roborock.vacuum_clean_segment
data:
  segments:
    - 16
    - 21
    - 16
    - 21
target:
  entity_id: vacuum.roborock_s7_maxv
```

The solution was to send the segments once and add a `repeat`-parameter like this:
```yaml
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - segments:
        - 16
        - 21
      repeat: 2
target:
  entity_id: vacuum.roborock_s7_maxv
```

I gave it a quick try and it seems to work.

Maybe `roborock.vacuum_clean_segment` can be enhanced to support `repeat` as well?
