### ISSUE TITLE
Start room cleaning with custom settings

### ISSUE THREAD

**Issue by Th3M1k3y** [humbertogontijo/homeassistant-roborock#162]
Is there a way to call a service to start room cleaning, but being able to define it so it only vacuum without mop?

My first try were to first call this
```
service: roborock.vacuum_set_mop_intensity
data:
  mop_intensity: "off"
target:
  device_id: redacted
```
then calling it to go clean a room.

But it still started by washing the mop, before going to just vacuum the room.

**Comment by robbinonline** [comment]
```
alias: Vacuum - Start only vacuum
sequence:
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: "off"
    target:
      entity_id: vacuum.X
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: roborock.vacuum_set_fan_speed
    data:
      fan_speed: balanced
    target:
      entity_id: vacuum.X
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: roborock.vacuum_clean_segment
     data:
     segments:
       - 1
    target:
  entity_id: vacuum.X

mode: single
icon: mdi:robot-vacuum
```

**Comment by JP13090** [comment]
That scripting helped me SO much!  Thank you, @robbinonline !

Any way to set the number of passes?

**Comment by Antexa** [comment]
Like this : 

```
{
  "domain": "xiaomi_miio",
  "service": "vacuum_clean_segment",
  "serviceData": {
    "segments": [
      "20",
      "20"
    ],
    "entity_id": "vacuum.roborock_s7_maxv"
  }
}
```

```
alias: Vacuum - Start only vacuum
sequence:
  - service: roborock.vacuum_set_mop_intensity
    data:
      mop_intensity: "off"
    target:
      entity_id: vacuum.X
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: roborock.vacuum_set_fan_speed
    data:
      fan_speed: balanced
    target:
      entity_id: vacuum.X
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: roborock.vacuum_clean_segment
     data:
     segments:[
      "1",
      "1"
    ],
    target:
      entity_id: vacuum.X
mode: single
icon: mdi:robot-vacuum
```
