### ISSUE TITLE
Not able to receive email confirmation code

### ISSUE THREAD

**Issue by and7ey** [humbertogontijo/homeassistant-roborock#164]
I am just not receiving an email with the code.

**Comment by and7ey** [comment]
I tried to repeat the requests you use manually.
It works in the following way:

1. `/api/v1/getUrlByEmail` returns the url (code 200, the url is `https://ruiot.roborock.com`)
2. `/api/v1/sendEmailCode` returns 200, but no mail is received (of course, I checked the spam folder ;))

I tried to pass the password manually to `/api/v1/login` and it returns `success`. 

Then I tried to manually use https://**eu**iot.roborock.com instead of https://**ru**iot.roborock.com when requesting the code and received the code immediately.

**Comment by humbertogontijo** [comment]
I'll add an option to use the password in config flow. It's possible to use the configuration.yaml to configure the integration, but you would need the whole user_data structure returned by the Roborock api, the username and the base_url.
Something like:
```
roborock:
  user_data:  
    <...entire user_data...>
  username: aaa1aaa@gmail.com
  base_url: https://ruiot.roborock.com
```
