### ISSUE TITLE
Grab additional maps

### ISSUE THREAD

**Issue by calvinbui** [humbertogontijo/homeassistant-roborock#17]
Roborock supports multiple maps, which is handy for people with multi-level homes. Currently, the integration has one 'camera' sensor which is the map selected inside the app. Is it possible to retrieve all each map and store it as a sensor?

**Comment by calvinbui** [comment]
The `load_multi_map` command no longer works on 0.0.2

**Comment by jdejaegh** [comment]
I updated to v 0.0.2 and it still works on my side.  Here is my service call (the same as [shown here before](https://github.com/humbertogontijo/homeassistant-roborock/issues/17#issuecomment-1351170455)) :

```yml
service: vacuum.send_command
data:
  command: load_multi_map
  params: 0
target:
  entity_id: vacuum.roborock_s7
```

When I change the value of `params` and call the service, the map changes in the Roborock app.
