### ISSUE TITLE
Fans speed turns null if "Indivual" is selected in the UI

### ISSUE THREAD

**Issue by Xyaren** [humbertogontijo/homeassistant-roborock#22]
When selecting the `Indiv.` option in the App the fan speed is null.
The option could be named different in the English verison. It is the last tab in the menu opened by the button in the lower right of the map screen.
This could be correct, as the speed would probably change per room.

Given, that the API is providing this information, this would require some kind of indication maybe by an additional attribute like `fan_speed_individual: true`.

Entity:

```yaml
fan_speed_list:
  - Silent
  - Balanced
  - Turbo
  - Max
battery_level: 89
battery_icon: mdi:battery-90
fan_speed: null
icon: mdi:robot-vacuum
friendly_name: Fussel
supported_features: 16383
```

Roborock S7
