### ISSUE TITLE
script for cleaning multiple rooms

### ISSUE THREAD

**Issue by Kijan** [humbertogontijo/homeassistant-roborock#252]
hi

I read this:
Action for making a roborock vacuum a specific room configured in the official app? #141
I got it working to clean rooms and so I added a script for each room.
Is it possible to put a helper in any way in the place where the room number has to go?
I would like to select rooms on my floorplan and with a delay or another button i would like to start the cleaning of the selected rooms.

**Comment by CH1PSET1** [comment]
Also interested in this moment. I would like to be able to select certain rooms for cleaning.

**Comment by Romario1972** [comment]
> I got it working to clean rooms and so I added a script for each room.

Could you please share your script for one room please?

**Comment by Kijan** [comment]
i created a script for each room like this:
`alias: Büro saugen
sequence:
  - service: roborock.vacuum_clean_segment
    data:
      segments:
        - 20
    target:
      entity_id: vacuum.sawi
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.vacuum_buro
mode: single
icon: mdi:robot-vacuum
`

**Comment by Kijan** [comment]
yeah but this is not flexibel.
i have an interface with a button for each room.
i would like to press all buttons for the rooms i like to clean and then it triggers, but i am not so deep in the coding to get the segments flexible

**Comment by blindguynar** [comment]
Although this says it's for the Xiaomi Mii integration it works perfectly fine for this integration as well and allows for cleaning multi-rooms.   It uses queuing so the script runs once for each room in sequence.  I still set-up a script for each room that in-turn calls the larger queued script though so i could easily see the buttons i pressed.  Although there are alternate ways to do this as well also.  

Only minor updates to the script were required (device id's, entity names, room names, etc) to make it work as it isn't specific to any integration. You create a number helper for each room (named specifically) and set it to the room segment id.  then call this script with that room name.  then call it again for the next room and it will queue those calls and execute them in-order until complete.  The runtime likely doesn't service a HA restart though as a note.

https://community.home-assistant.io/t/howto-buttons-for-room-cleaning-with-queuing-for-xiaomi-miio-robot-vacuum/320755

Hope this helps you out.

**Comment by Kijan** [comment]
thx i will try it ;)

**Comment by Klakurka** [comment]
> You can enter multiple segments to the service call:
> 
> ```
> sequence:
>   - service: roborock.vacuum_clean_segment
>     data:
>       segments:
>         - 16
>         - 17
>         - 18
>         - 19
>       repeats: 2
>     target:
>       entity_id: vacuum.roborock_s5_max
> ```

When I try this, it wakes up and leaves the dock but as soon as it backs out it just says it's done cleaning and goes back to dock.

Any ideas?

This is an S7 MaxV.

```
action:
  - service: vacuum.send_command
    data:
      command: app_segment_clean
      params:
        - segments:
            - 16
            - 17
        - repeat: 1
    target:
      entity_id: vacuum.cleaner
mode: single
```

**Comment by Lash-L** [comment]
@Klakurka make sure those segment ids are correct for you. And potentially remove the dash before repeats

**Comment by blindguynar** [comment]
Sorry i set it up awhile back, but it appears i changed the actual vac command to a service specific to this integration to originally get it working.  I just tested this simplified version of my script and it cleaned my kitchen without issue.  Please give it a shot.

in this case my segment id for kitchen is 16 and therefore i have a number helper called roborock_room_enum_kitchen that is set to the value 16 and i've set the script up to just have room kitchen and call the script for room kitchen.  

```
alias: Roborock Room Cleaning
max: 30
fields:
  room:
    name: Room
    required: true
    example: kitchen
    selector:
      select:
        options:
          - kitchen
sequence:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: vacuum.roborock_s7_maxv
                state: cleaning
              - condition: state
                entity_id: vacuum.roborock_s7_maxv
                state: error
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: vacuum.roborock_s7_maxv
                to: returning
              - platform: state
                entity_id: vacuum.roborock_s7_maxv
                to: docked
            continue_on_timeout: false
            timeout: "01:30:00"
          - service: roborock.vacuum_clean_segment
            data:
              segments: >
                {% set room_id = states("input_number.roborock_room_enum_" +
                room) | int %} {{ room_id }}
            target:
              entity_id: vacuum.roborock_s7_maxv
          - wait_for_trigger:
              - platform: state
                entity_id: vacuum.roborock_s7_maxv
                to: returning
              - platform: state
                entity_id: vacuum.roborock_s7_maxv
                to: docked
            continue_on_timeout: false
            timeout: "01:30:00"
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: vacuum.roborock_s7_maxv
                state: returning
              - condition: state
                entity_id: vacuum.roborock_s7_maxv
                state: docked
              - condition: state
                entity_id: vacuum.roborock_s7_maxv
                state: idle
        sequence:
          - service: roborock.vacuum_clean_segment
            data:
              segments: >
                {% set room_id = states("input_number.roborock_room_enum_" +
                room) | int %} {{ room_id }}
            target:
              entity_id: vacuum.roborock_s7_maxv
          - wait_for_trigger:
              - platform: state
                entity_id: vacuum.roborock_s7_maxv
                to: returning
              - platform: state
                entity_id: vacuum.roborock_s7_maxv
                to: docked
            continue_on_timeout: false
            timeout: "01:30:00"
    default: []
```

**Comment by Kijan** [comment]
> > yeah but this is not flexibel
> 
> It won't be more flexible, than being able to declare multiple rooms for the service call.

no if write the rooms directly in the script, it is not flexible at all. 
i cant choose the rooms on the dashboard.

**Comment by blindguynar** [comment]
> You can make a script which adding the rooms to the service call according to specific conditions. No need to create a script for every combination...
> 
> The problem with these script is, if you restart/reload HA the robot won't continue the cleaning, because HA sends the command to clean the next room after the robot finished with the current room. Also you can only stop the cleaning by aborting the script. For example, if you press the home button on the robot, it will start going to the dock, but HA will immediately send it to the next room.

Specific script per room?  Why would you do that?  I have one script for my entire top floor.  I call that one script and send it which room i want to clean.  Then call the same script again for the next room and it queues them.  There is just a SINGLE script so i don't know why you'd create more than one.  

Example of my main floor script showing many rooms within the same script.
```
  room:
    name: Room
    required: true
    example: kitchen
    selector:
      select:
        options:
          - kitchen
          - dining_room
          - master_bedroom
          - living_room
          - hall
          - laundry
          - office
          - guest_bedroom
          - hall_bathroom
sequence:
```

Return to Dock: That is just a button helper attached to an automation to stop the script, send the robot to the dock, and start the script.  It's a single button push and a simple automation.  From the app you're right.  Though i have an automation that will return the robot to the dock when it runs into issues too.  Basically i've not ran into the need to cancel it form the app verses just using a tablet dashboard.

i already mentioned it wouldn't survive a restart of HA so i can't solve that point.  In that case it will finish the room it's on and return to dock.  It will pick up next time on schedule so it's not like it's left in the middle of the room.  I don't find this as a huge deal for me and certainly it doesn't happen on the daily.  Your mileage certainly seems to vary from mine.

It seems to boil down to our definition of flexibility.  I don't consider predefined routes as flexible.  You don't and that's perfectly fine and meets your use case.  If you don't like the script you don't have to use it, but OP can also decide that for themselves as well.  You can certainly also write an even better one that also handles all the use cases, but with predefined segment lists it won't be quite as flexible under my definition of flexibility.

Basically OP had an issue open for 4 months for a specific requirement of flexibility, without a resolution.  I had a working solution that handles 95% of their use case so i thought i'd offer it to them.  Nothing more and nothing less.  Don't use it.  No one is forcing you to use it.
