### ISSUE TITLE
Vacuum rotation doesn't work

### ISSUE THREAD

**Issue by and7ey** [humbertogontijo/homeassistant-roborock#262]
<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.
## Version of the custom_component
0.1.2

## What vacuum are you using?
Roborock s7 (roborock.vacuum.a15, Firmware: 02.16.12)

## Describe the bug

the following commands don't rotate the vacuum
```
service: roborock.vacuum_remote_control_move_step
data:
  rotation: 179
target:
  entity_id: vacuum.roborock_s7  
```

```
service: roborock.vacuum_remote_control_move
data:
  rotation: 179
target:
  entity_id: vacuum.roborock_s7
```
(the mode is changed to remote and that's it)
