### ISSUE TITLE
State not updating, partial disconnection?

### ISSUE THREAD

**Issue by JoramHhub** [humbertogontijo/homeassistant-roborock#28]
I’ve noticed the state hardly gets updated. It does if you reload the integration and if you use the vacuum in the first hour or so after reloading. I’ve always chucked it up to starting the cleaning cycle from the Roborock app. But this morning my HA automation started the cleaning cycle for the first time. It had a connection as it did start the cleaning cycle but the state never updated, it said it was charging while the vacuum was running. Additionally the history didn’t record the cycle either, which is to be expected as the state never changed.

Anyone else seeing this too?

**Comment by Nezz** [comment]
Yes, I have the same. The new version spams less errors, but it still has this:
```
Logger: custom_components.roborock.api
Source: custom_components/roborock/api.py:178
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 13:31:50 (194 occurrences)
Last logged: 14:54:01
None
```

**Comment by humbertogontijo** [comment]
When using the mobile app messages are sent to this integration as well, and some of them are throwing exception when trying to decode it. I've added an except clause to any unexpected message for now. So it keep updating the entity even after an exception

**Comment by Nezz** [comment]
I added the automation for now that reloads the Roborock service every 3 hours:
```
alias: Schedule - Reload Roborock
description: ""
trigger:
  - platform: time_pattern
    hours: /3
condition: []
action:
  - service: homeassistant.reload_config_entry
    target: {}
    data:
      entry_id: e88640547021234322dd3db50f13f881
mode: single
```
