### ISSUE TITLE
[QUESTION] How to change the cleaning "mode"

### ISSUE THREAD

**Issue by jagjordi** [humbertogontijo/homeassistant-roborock#288]
I have a roborock S7. From the roborock app I can select few cleaning modes: vacuum, mop, vacuum+mop. I can also select diferent scrubbing intensity and mopping patterns. Is it possible to control those settings with this Integration?

**Comment by humbertogontijo** [comment]
Yes. You can play with vacuum fan speeds and mop modes. If you are using main branch there is a select entity for the mop mode. If you are using 0.1.2 there is a service for it

**Comment by StaleLoafOfBread** [comment]
@jagjordi I just upgraded to `v1.0.0` and updated my scripts for setting a "Vacuum as hard as possible" and "Mop as hard as possible". Maybe they will help you with your config.

``` yaml
alias: Vacuum Only Mode Max Plus
sequence:
  - service: select.select_option
    data:
      option: "off"
    target:
      entity_id: select.rosey_the_robot_mop_intensity
  - service: vacuum.set_fan_speed
    data:
      fan_speed: max_plus
    target:
      entity_id: vacuum.rosey_the_robot
  - wait_for_trigger:
      - platform: state
        entity_id:
          - vacuum.rosey_the_robot
        attribute: mop_intensity
        to: "off"
mode: restart
icon: mdi:vacuum
```

``` yaml
alias: Mop Only Mode Deep Plus
sequence:
  - service: vacuum.set_fan_speed
    data:
      fan_speed: "off"
    target:
      entity_id: vacuum.rosey_the_robot
  - service: select.select_option
    data:
      option: intense
    target:
      entity_id: select.rosey_the_robot_mop_intensity
  - service: select.select_option
    data:
      option: deep_plus
    target:
      entity_id: select.rosey_the_robot_mop_mode
  - wait_for_trigger:
      - platform: state
        entity_id:
          - vacuum.rosey_the_robot
        attribute: water_box_mode
        to: deep_plus
      - platform: state
        entity_id:
          - vacuum.rosey_the_robot
        attribute: mop_intensity
        to: intense
mode: restart
icon: mdi:water
```

The waits at the end might not be needed now that its local and (I assume) other optimizations. On v0.1.2 it helped remove any chance of a race condition which would occur occasionally.
