### ISSUE TITLE
Is there some kind of remote control planned?

### ISSUE THREAD

**Issue by gotschi** [humbertogontijo/homeassistant-roborock#362]
I tried moving my robot with the camera enabled in ui, using scripts I repeatedly call control start and move via button calls on the frontend. But this is far from reliable. The robot sometimes says remote control enabled, does the thing and disables rc again. other times it doesn't move at all.

## Describe the solution you'd like
The best thing would be a replicate of the control ui in the app (mainly just a joystick, direction buttons would probably satisfy)

## Vacuum
s6 maxv

thank you for this great component!! having video is awesome and the migration worked seamless!

**Comment by dscarr10** [comment]
I have had really good success setting up ptz control with the go2rtc add on, webrtc card, using the config example below on the webrtc card:

```
ptz:
  service: roborock.vacuum_remote_control_move
  data_left:
    duration: 0
    rotation: 30
    velocity: 0
    entity_id: vacuum.tank
  data_right:
    duration: 0
    rotation: -30
    velocity: 0
    entity_id: vacuum.tank
  data_up:
    duration: 1000
    rotation: 0
    velocity: 0.29
    entity_id: vacuum.tank
  data_down:
    duration: 1000
    rotation: 0
    velocity: -0.29
    entity_id: vacuum.tank
```
