### ISSUE TITLE
Map does not change until I start cleaning

### ISSUE THREAD

**Issue by saschabrockel** [humbertogontijo/homeassistant-roborock#423]
I'm referring to what I'm explaining here in the Xiaomi vacuum card but it has clearly something to do with Roborock / this component:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/633#discussioncomment-6518911

## Version of the custom_component
1.0.9

## What vacuum are you using?
Roborock S7

## Describe the bug

If I change the map in Home Assistant with the option to change the map by id but also when I change the map in the Roborock Android app the map won't update in the entity. It stays the same until I start cleaning. Then it will switch to the newly selected map. How can I fix it?

Home Assistant Core Integration: Update entity for the map doesn't work.

## Debug log

There are no logs for the map. Nothing happens (from the point I am now writing this I haven't started a cleaning)

```

**Comment by humbertogontijo** [comment]
The map only updates when the vacuum status is not docked. This is just to avoid calling the map every 5 seconds. If you change the map using the service roborock.load_multi_map it should update right away

**Comment by saschabrockel** [comment]
Alright I will try it or somehow combine it with switching the map and will tell you if it works.

**Comment by saschabrockel** [comment]
So @humbertogontijo do you mean that this should update the map instantly? If yes, it's not working. That is what I'm doing.

```
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 2
```

**Comment by humbertogontijo** [comment]
> So @humbertogontijo do you mean that this should update the map instantly? If yes, it's not working. That is what I'm doing.
> 
> 
> 
> ```
> 
>     tap_action:
> 
>       action: call-service
> 
>       service: vacuum.send_command
> 
>       service_data:
> 
>         entity_id: '[[entity_id]]'
> 
>         command: load_multi_map
> 
>         params: 2
> 
> ```

Not with vacuum.send_command. Use roborock.load_multi_map service

**Comment by saschabrockel** [comment]
The command is named `roborock.vacuum_load_multi_map` for me but it works now! The sensor for the map name still needs a while to update but that's no problem.

```
    tap_action:
      action: call-service
      service: roborock.vacuum_load_multi_map
      service_data:
        entity_id: '[[entity_id]]'
        map_flag: 0
```
