### ISSUE TITLE
What happened to roborock.vacuum_set_mop_intensity?

### ISSUE THREAD

**Issue by ultimateguy** [humbertogontijo/homeassistant-roborock#426]
I have an automation that uses the service roborock.vacuum_set_mop_intensity but the service seems to have disappeared. Is there a new way to use this functionality?

**Comment by humbertogontijo** [comment]
Yes.
Use something like this
```
service: select.select_option
data:
  option: custom
target:
  entity_id: select.roborock_s7_maxv_mop_intensity

```
