### ISSUE TITLE
Segments must be unique (I assume)

### ISSUE THREAD

**Issue by kbrown01** [humbertogontijo/homeassistant-roborock#527]
Without looking deeply in the code, and just testing through developer tools ... this will clean segment "17" only once:

```
service: roborock.vacuum_clean_segment
data:
  segments:
    - 17
    - 17
    - 17
target:
  entity_id: vacuum.roborock_s7
```

Ideally, it would be great if either you could list a segment multiple times, or better the constructor could be like:

```
- segment: 17
  repeat: 2
- segment: 18
  repeat: 1
- segment: 19
  repeat: 3
```
