### ISSUE TITLE
Room selection

### ISSUE THREAD

**Issue by darth-aragoth** [humbertogontijo/homeassistant-roborock#613]
I use Roborock S6, in Roborock app I defined two floors, every floor with named rooms. How can I select floor / room for cleaning? I can find current floor / room in device attributes, but I don't know, how to send my vacuum to the chosen room.

**Comment by kaiserkiwi** [comment]
As far as I'm aware you only can access them via IDs that are never exposed. It's a bit weird, but try to find the right IDs.

Looks like this.
```yaml
service: roborock.vacuum_clean_segment
    data:
      segments: 18
    target:
      device_id: YOUR_DEVICE_ID
```
