### ISSUE TITLE
The margin around the map are to big.

### ISSUE THREAD

**Issue by cybernard** [humbertogontijo/homeassistant-roborock#684]
## Version of the custom_component
Current verison

## What vacuum are you using?
Roborock S7 max

## Describe the bug

The map is very small because there is a huge blue boarder around the image.  Please reduce the blue boarder to no more than 10px.
I have blocked out the map for privacy reasons, but there is as much boarder as map.

![Image](https://github.com/user-attachments/assets/c39a5c16-aa72-4134-8489-7286b5e4bed9)

## Debug log

```text

Add your logs here.

```

**Comment by Laho812** [comment]
You  can add `crop` to your `map_source:`

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s7_maxv_map
  crop:
    top: 100
    left: 120
    right: 125
    bottom: 80
calibration_source:
  camera: true
entity: vacuum.roborock_s7_maxv
vacuum_platform: humbertogontijo/homeassistant-roborock

```
