### ISSUE TITLE
Unable to setup vac + mop S7 max

### ISSUE THREAD

**Issue by xgenosis** [humbertogontijo/homeassistant-roborock#710]
Hi folks,

I'm having issues with trying to get vac + mop working. Vac by itself works fine so clearly I'm doing something wrong. here is the script I'm using. i thought this would. Any help would be appreciated

```
alias: Mop Kitchen
sequence:
  - service: vacuum.send_command
    data:
      command: set_clean_mode
      params: [3]  # mop only
    target:
      entity_id: vacuum.s7_roborock

  - delay: 2

  - service: vacuum.send_command
    data:
      command: set_mop_intensity
      params: [2]  # high
    target:
      entity_id: vacuum.s7_roborock

  - delay: 2

  - service: vacuum.send_command
    data:
      command: app_segment_clean
      params:
        - segments: [22]
          repeat: 1
    target:
      entity_id: vacuum.s7_roborock

```
